INSERT INTO `distrito_cr` (`codigo_distrito`,`canton_id`,`nombre_distrito`) VALUES 
 ('01',(select id from canton_cr where codigo_canton ='01' and provincia_id = 1),'Carmen'),
 ('02',(select id from canton_cr where codigo_canton ='01' and provincia_id = 1),'Merced'),
 ('03',(select id from canton_cr where codigo_canton ='01' and provincia_id = 1),'Hospital'),
 ('04',(select id from canton_cr where codigo_canton ='01' and provincia_id = 1),'Catedral'),
 ('05',(select id from canton_cr where codigo_canton ='01' and provincia_id = 1),'Zapote'),
 ('06',(select id from canton_cr where codigo_canton ='01' and provincia_id = 1),'San Francisco de Dos Ríos'),
 ('07',(select id from canton_cr where codigo_canton ='01' and provincia_id = 1),'Uruca'),
 ('08',(select id from canton_cr where codigo_canton ='01' and provincia_id = 1),'Mata Redonda'),
 ('09',(select id from canton_cr where codigo_canton ='01' and provincia_id = 1),'Pavas'),
 ('10',(select id from canton_cr where codigo_canton ='01' and provincia_id = 1),'Hatillo'),
 ('11',(select id from canton_cr where codigo_canton ='01' and provincia_id = 1),'San Sebastián'),
 ('01',(select id from canton_cr where codigo_canton ='02' and provincia_id = 1),'Escazú'),
 ('02',(select id from canton_cr where codigo_canton ='02' and provincia_id = 1),'San Antonio'),
 ('03',(select id from canton_cr where codigo_canton ='02' and provincia_id = 1),'San Rafael'),
 ('01',(select id from canton_cr where codigo_canton ='03' and provincia_id = 1),'Desamparados'),
 ('02',(select id from canton_cr where codigo_canton ='03' and provincia_id = 1),'San Miguel'),
 ('03',(select id from canton_cr where codigo_canton ='03' and provincia_id = 1),'San Juan de Dios'),
 ('04',(select id from canton_cr where codigo_canton ='03' and provincia_id = 1),'San Rafael Arriba'),
 ('05',(select id from canton_cr where codigo_canton ='03' and provincia_id = 1),'San Antonio'),
 ('06',(select id from canton_cr where codigo_canton ='03' and provincia_id = 1),'Frailes'),
 ('07',(select id from canton_cr where codigo_canton ='03' and provincia_id = 1),'Patarrá'),
 ('08',(select id from canton_cr where codigo_canton ='03' and provincia_id = 1),'San Cristóbal'),
 ('09',(select id from canton_cr where codigo_canton ='03' and provincia_id = 1),'Rosario'),
 ('10',(select id from canton_cr where codigo_canton ='03' and provincia_id = 1),'Damas'),
 ('11',(select id from canton_cr where codigo_canton ='03' and provincia_id = 1),'San Rafael Abajo'),
 ('12',(select id from canton_cr where codigo_canton ='03' and provincia_id = 1),'Gravilias'),
 ('13',(select id from canton_cr where codigo_canton ='03' and provincia_id = 1),'Los Guido'),
 ('01',(select id from canton_cr where codigo_canton ='04' and provincia_id = 1),'Santiago'),
 ('02',(select id from canton_cr where codigo_canton ='04' and provincia_id = 1),'Mercedes Sur'),
 ('03',(select id from canton_cr where codigo_canton ='04' and provincia_id = 1),'Barbacoas'),
 ('04',(select id from canton_cr where codigo_canton ='04' and provincia_id = 1),'Grifo Alto'),
 ('05',(select id from canton_cr where codigo_canton ='04' and provincia_id = 1),'San Rafael'),
 ('06',(select id from canton_cr where codigo_canton ='04' and provincia_id = 1),'Candelaria'),
 ('07',(select id from canton_cr where codigo_canton ='04' and provincia_id = 1),'Desamparaditos'),
 ('08',(select id from canton_cr where codigo_canton ='04' and provincia_id = 1),'San Antonio'),
 ('09',(select id from canton_cr where codigo_canton ='04' and provincia_id = 1),'Chires'),
 ('01',(select id from canton_cr where codigo_canton ='05' and provincia_id = 1),'San Marcos'),
 ('02',(select id from canton_cr where codigo_canton ='05' and provincia_id = 1),'San Lorenzo'),
 ('03',(select id from canton_cr where codigo_canton ='05' and provincia_id = 1),'San Carlos'),
 ('01',(select id from canton_cr where codigo_canton ='06' and provincia_id = 1),'Aserrí'),
 ('02',(select id from canton_cr where codigo_canton ='06' and provincia_id = 1),'Tarbaca o Praga'),
 ('03',(select id from canton_cr where codigo_canton ='06' and provincia_id = 1),'Vuelta de Jorco'),
 ('04',(select id from canton_cr where codigo_canton ='06' and provincia_id = 1),'San Gabriel'),
 ('05',(select id from canton_cr where codigo_canton ='06' and provincia_id = 1),'La Legua'),
 ('06',(select id from canton_cr where codigo_canton ='06' and provincia_id = 1),'Monterrey'),
 ('07',(select id from canton_cr where codigo_canton ='06' and provincia_id = 1),'Salitrillos'),
 ('01',(select id from canton_cr where codigo_canton ='07' and provincia_id = 1),'Colón'),
 ('02',(select id from canton_cr where codigo_canton ='07' and provincia_id = 1),'Guayabo'),
 ('03',(select id from canton_cr where codigo_canton ='07' and provincia_id = 1),'Tabarcia'),
 ('04',(select id from canton_cr where codigo_canton ='07' and provincia_id = 1),'Piedras Negras'),
 ('05',(select id from canton_cr where codigo_canton ='07' and provincia_id = 1),'Picagres'),
 ('01',(select id from canton_cr where codigo_canton ='08' and provincia_id = 1),'Guadalupe'),
 ('02',(select id from canton_cr where codigo_canton ='08' and provincia_id = 1),'San Francisco'),
 ('03',(select id from canton_cr where codigo_canton ='08' and provincia_id = 1),'Calle Blancos'),
 ('04',(select id from canton_cr where codigo_canton ='08' and provincia_id = 1),'Mata de Plátano'),
 ('05',(select id from canton_cr where codigo_canton ='08' and provincia_id = 1),'Ipís'),
 ('06',(select id from canton_cr where codigo_canton ='08' and provincia_id = 1),'Rancho Redondo'),
 ('07',(select id from canton_cr where codigo_canton ='08' and provincia_id = 1),'Purral'),
 ('01',(select id from canton_cr where codigo_canton ='09' and provincia_id = 1),'Santa Ana'),
 ('02',(select id from canton_cr where codigo_canton ='09' and provincia_id = 1),'Salitral'),
 ('03',(select id from canton_cr where codigo_canton ='09' and provincia_id = 1),'Pozos o Concepción'),
 ('04',(select id from canton_cr where codigo_canton ='09' and provincia_id = 1),'Uruca o San Joaquín'),
 ('05',(select id from canton_cr where codigo_canton ='09' and provincia_id = 1),'Piedades'),
 ('06',(select id from canton_cr where codigo_canton ='09' and provincia_id = 1),'Brasil'),
 ('01',(select id from canton_cr where codigo_canton ='10' and provincia_id = 1),'Alajuelita'),
 ('02',(select id from canton_cr where codigo_canton ='10' and provincia_id = 1),'San Josecito'),
 ('03',(select id from canton_cr where codigo_canton ='10' and provincia_id = 1),'San Antonio'),
 ('04',(select id from canton_cr where codigo_canton ='10' and provincia_id = 1),'Concepción'),
 ('05',(select id from canton_cr where codigo_canton ='10' and provincia_id = 1),'San Felipe'),
 ('01',(select id from canton_cr where codigo_canton ='11' and provincia_id = 1),'San Isidro'),
 ('02',(select id from canton_cr where codigo_canton ='11' and provincia_id = 1),'San Rafael'),
 ('03',(select id from canton_cr where codigo_canton ='11' and provincia_id = 1),'Dulce Nombre de Jesús'),
 ('04',(select id from canton_cr where codigo_canton ='11' and provincia_id = 1),'Patalillo'),
 ('05',(select id from canton_cr where codigo_canton ='11' and provincia_id = 1),'Cascajal'),
 ('01',(select id from canton_cr where codigo_canton ='12' and provincia_id = 1),'San Ignacio'),
 ('02',(select id from canton_cr where codigo_canton ='12' and provincia_id = 1),'Guaitil'),
 ('03',(select id from canton_cr where codigo_canton ='12' and provincia_id = 1),'Palmichal'),
 ('04',(select id from canton_cr where codigo_canton ='12' and provincia_id = 1),'Cangrejal'),
 ('05',(select id from canton_cr where codigo_canton ='12' and provincia_id = 1),'Sabanillas'),
 ('01',(select id from canton_cr where codigo_canton ='13' and provincia_id = 1),'San Juan'),
 ('02',(select id from canton_cr where codigo_canton ='13' and provincia_id = 1),'Cinco Esquinas'),
 ('03',(select id from canton_cr where codigo_canton ='13' and provincia_id = 1),'Anselmo Llorente'),
 ('04',(select id from canton_cr where codigo_canton ='13' and provincia_id = 1),'León XIII'),
 ('05',(select id from canton_cr where codigo_canton ='13' and provincia_id = 1),'Colima'),
 ('01',(select id from canton_cr where codigo_canton ='14' and provincia_id = 1),'San Vicente'),
 ('02',(select id from canton_cr where codigo_canton ='14' and provincia_id = 1),'San Jerónimo'),
 ('03',(select id from canton_cr where codigo_canton ='14' and provincia_id = 1),'Trinidad'),
 ('01',(select id from canton_cr where codigo_canton ='15' and provincia_id = 1),'San Pedro'),
 ('02',(select id from canton_cr where codigo_canton ='15' and provincia_id = 1),'Sabanilla'),
 ('03',(select id from canton_cr where codigo_canton ='15' and provincia_id = 1),'Mercedes o Betania'),
 ('04',(select id from canton_cr where codigo_canton ='15' and provincia_id = 1),'San Rafael'),
 ('01',(select id from canton_cr where codigo_canton ='16' and provincia_id = 1),'San Pablo'),
 ('02',(select id from canton_cr where codigo_canton ='16' and provincia_id = 1),'San Pedro'),
 ('03',(select id from canton_cr where codigo_canton ='16' and provincia_id = 1),'San Juan de Mata'),
 ('04',(select id from canton_cr where codigo_canton ='16' and provincia_id = 1),'San Luis'),
 ('05',(select id from canton_cr where codigo_canton ='16' and provincia_id = 1),'Cárara'),
 ('01',(select id from canton_cr where codigo_canton ='17' and provincia_id = 1),'Santa María'),
 ('02',(select id from canton_cr where codigo_canton ='17' and provincia_id = 1),'Jardín'),
 ('03',(select id from canton_cr where codigo_canton ='17' and provincia_id = 1),'Copey'),
 ('01',(select id from canton_cr where codigo_canton ='18' and provincia_id = 1),'Curridabat'),
 ('02',(select id from canton_cr where codigo_canton ='18' and provincia_id = 1),'Granadilla'),
 ('03',(select id from canton_cr where codigo_canton ='18' and provincia_id = 1),'Sánchez'),
 ('04',(select id from canton_cr where codigo_canton ='18' and provincia_id = 1),'Tirrases'),
 ('01',(select id from canton_cr where codigo_canton ='19' and provincia_id = 1),'San Isidro de el General'),
 ('02',(select id from canton_cr where codigo_canton ='19' and provincia_id = 1),'General'),
 ('03',(select id from canton_cr where codigo_canton ='19' and provincia_id = 1),'Daniel Flores'),
 ('04',(select id from canton_cr where codigo_canton ='19' and provincia_id = 1),'Rivas'),
 ('05',(select id from canton_cr where codigo_canton ='19' and provincia_id = 1),'San Pedro'),
 ('06',(select id from canton_cr where codigo_canton ='19' and provincia_id = 1),'Platanares'),
 ('07',(select id from canton_cr where codigo_canton ='19' and provincia_id = 1),'Pejibaye'),
 ('08',(select id from canton_cr where codigo_canton ='19' and provincia_id = 1),'Cajón'),
 ('09',(select id from canton_cr where codigo_canton ='19' and provincia_id = 1),'Barú'),
 ('10',(select id from canton_cr where codigo_canton ='19' and provincia_id = 1),'Río Nuevo'),
 ('11',(select id from canton_cr where codigo_canton ='19' and provincia_id = 1),'Páramo'),
 ('01',(select id from canton_cr where codigo_canton ='20' and provincia_id = 1),'San Pablo'),
 ('02',(select id from canton_cr where codigo_canton ='20' and provincia_id = 1),'San Andrés'),
 ('03',(select id from canton_cr where codigo_canton ='20' and provincia_id = 1),'Llano Bonito'),
 ('04',(select id from canton_cr where codigo_canton ='20' and provincia_id = 1),'San Isidro'),
 ('05',(select id from canton_cr where codigo_canton ='20' and provincia_id = 1),'Santa Cruz'),
 ('06',(select id from canton_cr where codigo_canton ='20' and provincia_id = 1),'San Antonio'),
 ('01',(select id from canton_cr where codigo_canton ='01' and provincia_id = 2),'Alajuela'),
 ('02',(select id from canton_cr where codigo_canton ='01' and provincia_id = 2),'San José'),
 ('03',(select id from canton_cr where codigo_canton ='01' and provincia_id = 2),'Carrizal'),
 ('04',(select id from canton_cr where codigo_canton ='01' and provincia_id = 2),'San Antonio'),
 ('05',(select id from canton_cr where codigo_canton ='01' and provincia_id = 2),'Guácima'),
 ('06',(select id from canton_cr where codigo_canton ='01' and provincia_id = 2),'San Isidro'),
 ('07',(select id from canton_cr where codigo_canton ='01' and provincia_id = 2),'Sabanilla'),
 ('08',(select id from canton_cr where codigo_canton ='01' and provincia_id = 2),'San Rafael'),
 ('09',(select id from canton_cr where codigo_canton ='01' and provincia_id = 2),'Río Segundo'),
 ('10',(select id from canton_cr where codigo_canton ='01' and provincia_id = 2),'Desamparados'),
 ('11',(select id from canton_cr where codigo_canton ='01' and provincia_id = 2),'Turrucares'),
 ('12',(select id from canton_cr where codigo_canton ='01' and provincia_id = 2),'Tambor'),
 ('13',(select id from canton_cr where codigo_canton ='01' and provincia_id = 2),'La Garita'),
 ('14',(select id from canton_cr where codigo_canton ='01' and provincia_id = 2),'Sarapiquí'),
 ('01',(select id from canton_cr where codigo_canton ='02' and provincia_id = 2),'San Ramón'),
 ('02',(select id from canton_cr where codigo_canton ='02' and provincia_id = 2),'Santiago'),
 ('03',(select id from canton_cr where codigo_canton ='02' and provincia_id = 2),'San Juan'),
 ('04',(select id from canton_cr where codigo_canton ='02' and provincia_id = 2),'Piedades Norte'),
 ('05',(select id from canton_cr where codigo_canton ='02' and provincia_id = 2),'Piedades Sur'),
 ('06',(select id from canton_cr where codigo_canton ='02' and provincia_id = 2),'San Rafael'),
 ('07',(select id from canton_cr where codigo_canton ='02' and provincia_id = 2),'San Isidro'),
 ('08',(select id from canton_cr where codigo_canton ='02' and provincia_id = 2),'Angeles'),
 ('09',(select id from canton_cr where codigo_canton ='02' and provincia_id = 2),'Alfaro'),
 ('10',(select id from canton_cr where codigo_canton ='02' and provincia_id = 2),'Volio'),
 ('11',(select id from canton_cr where codigo_canton ='02' and provincia_id = 2),'Concepción'),
 ('12',(select id from canton_cr where codigo_canton ='02' and provincia_id = 2),'Zapotal'),
 ('13',(select id from canton_cr where codigo_canton ='02' and provincia_id = 2),'San Isidro de Peñas Blancas'),
 ('01',(select id from canton_cr where codigo_canton ='03' and provincia_id = 2),'Grecia'),
 ('02',(select id from canton_cr where codigo_canton ='03' and provincia_id = 2),'San Isidro'),
 ('03',(select id from canton_cr where codigo_canton ='03' and provincia_id = 2),'San José'),
 ('04',(select id from canton_cr where codigo_canton ='03' and provincia_id = 2),'San Roque'),
 ('05',(select id from canton_cr where codigo_canton ='03' and provincia_id = 2),'Tacares'),
 ('06',(select id from canton_cr where codigo_canton ='03' and provincia_id = 2),'Río Cuarto'),
 ('07',(select id from canton_cr where codigo_canton ='03' and provincia_id = 2),'Puente Piedra'),
 ('08',(select id from canton_cr where codigo_canton ='03' and provincia_id = 2),'Bolívar'),
 ('01',(select id from canton_cr where codigo_canton ='04' and provincia_id = 2),'San Mateo'),
 ('02',(select id from canton_cr where codigo_canton ='04' and provincia_id = 2),'Desmonte'),
 ('03',(select id from canton_cr where codigo_canton ='04' and provincia_id = 2),'Jesús María'),
 ('01',(select id from canton_cr where codigo_canton ='05' and provincia_id = 2),'Atenas'),
 ('02',(select id from canton_cr where codigo_canton ='05' and provincia_id = 2),'Jesús'),
 ('03',(select id from canton_cr where codigo_canton ='05' and provincia_id = 2),'Mercedes'),
 ('04',(select id from canton_cr where codigo_canton ='05' and provincia_id = 2),'San Isidro'),
 ('05',(select id from canton_cr where codigo_canton ='05' and provincia_id = 2),'Concepción'),
 ('06',(select id from canton_cr where codigo_canton ='05' and provincia_id = 2),'San José'),
 ('07',(select id from canton_cr where codigo_canton ='05' and provincia_id = 2),'Santa Eulalia'),
 ('08',(select id from canton_cr where codigo_canton ='05' and provincia_id = 2),'Escobal'),
 ('01',(select id from canton_cr where codigo_canton ='06' and provincia_id = 2),'Naranjo'),
 ('02',(select id from canton_cr where codigo_canton ='06' and provincia_id = 2),'San Miguel'),
 ('03',(select id from canton_cr where codigo_canton ='06' and provincia_id = 2),'San José'),
 ('04',(select id from canton_cr where codigo_canton ='06' and provincia_id = 2),'Cirrí Sur'),
 ('05',(select id from canton_cr where codigo_canton ='06' and provincia_id = 2),'San Jerónimo'),
 ('06',(select id from canton_cr where codigo_canton ='06' and provincia_id = 2),'San Juan'),
 ('07',(select id from canton_cr where codigo_canton ='06' and provincia_id = 2),'Rosario'),
 ('01',(select id from canton_cr where codigo_canton ='07' and provincia_id = 2),'Palmares'),
 ('02',(select id from canton_cr where codigo_canton ='07' and provincia_id = 2),'Zaragoza'),
 ('03',(select id from canton_cr where codigo_canton ='07' and provincia_id = 2),'Buenos Aires'),
 ('04',(select id from canton_cr where codigo_canton ='07' and provincia_id = 2),'Santiago'),
 ('05',(select id from canton_cr where codigo_canton ='07' and provincia_id = 2),'Candelaria'),
 ('06',(select id from canton_cr where codigo_canton ='07' and provincia_id = 2),'Esquipulas'),
 ('07',(select id from canton_cr where codigo_canton ='07' and provincia_id = 2),'La Granja'),
 ('01',(select id from canton_cr where codigo_canton ='08' and provincia_id = 2),'San Pedro'),
 ('02',(select id from canton_cr where codigo_canton ='08' and provincia_id = 2),'San Juan'),
 ('03',(select id from canton_cr where codigo_canton ='08' and provincia_id = 2),'San Rafael'),
 ('04',(select id from canton_cr where codigo_canton ='08' and provincia_id = 2),'Carrillos'),
 ('05',(select id from canton_cr where codigo_canton ='08' and provincia_id = 2),'Sabana Redonda'),
 ('01',(select id from canton_cr where codigo_canton ='09' and provincia_id = 2),'Orotina'),
 ('02',(select id from canton_cr where codigo_canton ='09' and provincia_id = 2),'Mastate'),
 ('03',(select id from canton_cr where codigo_canton ='09' and provincia_id = 2),'Hacienda Vieja'),
 ('04',(select id from canton_cr where codigo_canton ='09' and provincia_id = 2),'Coyolar'),
 ('05',(select id from canton_cr where codigo_canton ='09' and provincia_id = 2),'Ceiba'),
 ('01',(select id from canton_cr where codigo_canton ='10' and provincia_id = 2),'Quesada'),
 ('02',(select id from canton_cr where codigo_canton ='10' and provincia_id = 2),'Florencia'),
 ('03',(select id from canton_cr where codigo_canton ='10' and provincia_id = 2),'Buenavista'),
 ('04',(select id from canton_cr where codigo_canton ='10' and provincia_id = 2),'Aguas Zarcas'),
 ('05',(select id from canton_cr where codigo_canton ='10' and provincia_id = 2),'Venecia'),
 ('06',(select id from canton_cr where codigo_canton ='10' and provincia_id = 2),'Pital'),
 ('07',(select id from canton_cr where codigo_canton ='10' and provincia_id = 2),'Fortuna'),
 ('08',(select id from canton_cr where codigo_canton ='10' and provincia_id = 2),'Tigra'),
 ('09',(select id from canton_cr where codigo_canton ='10' and provincia_id = 2),'Palmera'),
 ('10',(select id from canton_cr where codigo_canton ='10' and provincia_id = 2),'Venado'),
 ('11',(select id from canton_cr where codigo_canton ='10' and provincia_id = 2),'Cutris'),
 ('12',(select id from canton_cr where codigo_canton ='10' and provincia_id = 2),'Monterrey'),
 ('13',(select id from canton_cr where codigo_canton ='10' and provincia_id = 2),'Pocosol'),
 ('01',(select id from canton_cr where codigo_canton ='11' and provincia_id = 2),'Zarcero'),
 ('02',(select id from canton_cr where codigo_canton ='11' and provincia_id = 2),'Laguna'),
 ('03',(select id from canton_cr where codigo_canton ='11' and provincia_id = 2),'Tapezco'),
 ('04',(select id from canton_cr where codigo_canton ='11' and provincia_id = 2),'Guadalupe'),
 ('05',(select id from canton_cr where codigo_canton ='11' and provincia_id = 2),'Palmira'),
 ('06',(select id from canton_cr where codigo_canton ='11' and provincia_id = 2),'Zapote'),
 ('07',(select id from canton_cr where codigo_canton ='11' and provincia_id = 2),'Las Brisas'),
 ('01',(select id from canton_cr where codigo_canton ='12' and provincia_id = 2),'Sarchí Norte'),
 ('02',(select id from canton_cr where codigo_canton ='12' and provincia_id = 2),'Sarchí Sur'),
 ('03',(select id from canton_cr where codigo_canton ='12' and provincia_id = 2),'Toro Amarillo'),
 ('04',(select id from canton_cr where codigo_canton ='12' and provincia_id = 2),'San Pedro'),
 ('05',(select id from canton_cr where codigo_canton ='12' and provincia_id = 2),'Rodríguez'),
 ('01',(select id from canton_cr where codigo_canton ='13' and provincia_id = 2),'Upala'),
 ('02',(select id from canton_cr where codigo_canton ='13' and provincia_id = 2),'Aguas Claras'),
 ('03',(select id from canton_cr where codigo_canton ='13' and provincia_id = 2),'San José o Pizote'),
 ('04',(select id from canton_cr where codigo_canton ='13' and provincia_id = 2),'Bijagua'),
 ('05',(select id from canton_cr where codigo_canton ='13' and provincia_id = 2),'Delicias'),
 ('06',(select id from canton_cr where codigo_canton ='13' and provincia_id = 2),'Dos Ríos'),
 ('07',(select id from canton_cr where codigo_canton ='13' and provincia_id = 2),'Yolillal'),
 ('01',(select id from canton_cr where codigo_canton ='14' and provincia_id = 2),'Los Chiles'),
 ('02',(select id from canton_cr where codigo_canton ='14' and provincia_id = 2),'Caño Negro'),
 ('03',(select id from canton_cr where codigo_canton ='14' and provincia_id = 2),'Amparo'),
 ('04',(select id from canton_cr where codigo_canton ='14' and provincia_id = 2),'San Jorge'),
 ('01',(select id from canton_cr where codigo_canton ='15' and provincia_id = 2),'San Rafael'),
 ('02',(select id from canton_cr where codigo_canton ='15' and provincia_id = 2),'Buenavista'),
 ('03',(select id from canton_cr where codigo_canton ='15' and provincia_id = 2),'Cote'),
 ('01',(select id from canton_cr where codigo_canton ='01' and provincia_id = 3),'Oriental'),
 ('02',(select id from canton_cr where codigo_canton ='01' and provincia_id = 3),'Occidental'),
 ('03',(select id from canton_cr where codigo_canton ='01' and provincia_id = 3),'Carmen'),
 ('04',(select id from canton_cr where codigo_canton ='01' and provincia_id = 3),'San Nicolás'),
 ('05',(select id from canton_cr where codigo_canton ='01' and provincia_id = 3),'Aguacaliente o San Francisco'),
 ('06',(select id from canton_cr where codigo_canton ='01' and provincia_id = 3),'Guadalupe o Arenilla'),
 ('07',(select id from canton_cr where codigo_canton ='01' and provincia_id = 3),'Corralillo'),
 ('08',(select id from canton_cr where codigo_canton ='01' and provincia_id = 3),'Tierra Blanca'),
 ('09',(select id from canton_cr where codigo_canton ='01' and provincia_id = 3),'Dulce Nombre'),
 ('10',(select id from canton_cr where codigo_canton ='01' and provincia_id = 3),'Llano Grande'),
 ('11',(select id from canton_cr where codigo_canton ='01' and provincia_id = 3),'Quebradilla'),
 ('01',(select id from canton_cr where codigo_canton ='02' and provincia_id = 3),'Paraíso'),
 ('02',(select id from canton_cr where codigo_canton ='02' and provincia_id = 3),'Santiago'),
 ('03',(select id from canton_cr where codigo_canton ='02' and provincia_id = 3),'Orosi'),
 ('04',(select id from canton_cr where codigo_canton ='02' and provincia_id = 3),'Cachí'),
 ('05',(select id from canton_cr where codigo_canton ='02' and provincia_id = 3),'Los Llanos de Santa Lucía'),
 ('01',(select id from canton_cr where codigo_canton ='03' and provincia_id = 3),'Tres Ríos'),
 ('02',(select id from canton_cr where codigo_canton ='03' and provincia_id = 3),'San Diego'),
 ('03',(select id from canton_cr where codigo_canton ='03' and provincia_id = 3),'San Juan'),
 ('04',(select id from canton_cr where codigo_canton ='03' and provincia_id = 3),'San Rafael'),
 ('05',(select id from canton_cr where codigo_canton ='03' and provincia_id = 3),'Concepción'),
 ('06',(select id from canton_cr where codigo_canton ='03' and provincia_id = 3),'Dulce Nombre'),
 ('07',(select id from canton_cr where codigo_canton ='03' and provincia_id = 3),'San Ramón'),
 ('08',(select id from canton_cr where codigo_canton ='03' and provincia_id = 3),'Río Azul'),
 ('01',(select id from canton_cr where codigo_canton ='04' and provincia_id = 3),'Juan Viñas'),
 ('02',(select id from canton_cr where codigo_canton ='04' and provincia_id = 3),'Tucurrique'),
 ('03',(select id from canton_cr where codigo_canton ='04' and provincia_id = 3),'Pejibaye'),
 ('01',(select id from canton_cr where codigo_canton ='05' and provincia_id = 3),'Turrialba'),
 ('02',(select id from canton_cr where codigo_canton ='05' and provincia_id = 3),'La Suiza'),
 ('03',(select id from canton_cr where codigo_canton ='05' and provincia_id = 3),'Peralta'),
 ('04',(select id from canton_cr where codigo_canton ='05' and provincia_id = 3),'Santa Cruz'),
 ('05',(select id from canton_cr where codigo_canton ='05' and provincia_id = 3),'Santa Teresita'),
 ('06',(select id from canton_cr where codigo_canton ='05' and provincia_id = 3),'Pavones'),
 ('07',(select id from canton_cr where codigo_canton ='05' and provincia_id = 3),'Tuis'),
 ('08',(select id from canton_cr where codigo_canton ='05' and provincia_id = 3),'Tayutic'),
 ('09',(select id from canton_cr where codigo_canton ='05' and provincia_id = 3),'Santa Rosa'),
 ('10',(select id from canton_cr where codigo_canton ='05' and provincia_id = 3),'Tres Equis'),
 ('11',(select id from canton_cr where codigo_canton ='05' and provincia_id = 3),'La Isabel'),
 ('12',(select id from canton_cr where codigo_canton ='05' and provincia_id = 3),'Chirripó'),
 ('01',(select id from canton_cr where codigo_canton ='06' and provincia_id = 3),'Pacayas'),
 ('02',(select id from canton_cr where codigo_canton ='06' and provincia_id = 3),'Cervantes'),
 ('03',(select id from canton_cr where codigo_canton ='06' and provincia_id = 3),'Capellades'),
 ('01',(select id from canton_cr where codigo_canton ='07' and provincia_id = 3),'San Rafael'),
 ('02',(select id from canton_cr where codigo_canton ='07' and provincia_id = 3),'Cot'),
 ('03',(select id from canton_cr where codigo_canton ='07' and provincia_id = 3),'Potrero Cerrado'),
 ('04',(select id from canton_cr where codigo_canton ='07' and provincia_id = 3),'Cipreses'),
 ('05',(select id from canton_cr where codigo_canton ='07' and provincia_id = 3),'Santa Rosa'),
 ('01',(select id from canton_cr where codigo_canton ='08' and provincia_id = 3),'El Tejar'),
 ('02',(select id from canton_cr where codigo_canton ='08' and provincia_id = 3),'San Isidro'),
 ('03',(select id from canton_cr where codigo_canton ='08' and provincia_id = 3),'Tobosi'),
 ('04',(select id from canton_cr where codigo_canton ='08' and provincia_id = 3),'Patio de Agua'),
 ('01',(select id from canton_cr where codigo_canton ='01' and provincia_id = 4),'Heredia'),
 ('02',(select id from canton_cr where codigo_canton ='01' and provincia_id = 4),'Mercedes'),
 ('03',(select id from canton_cr where codigo_canton ='01' and provincia_id = 4),'San Francisco'),
 ('04',(select id from canton_cr where codigo_canton ='01' and provincia_id = 4),'Ulloa'),
 ('05',(select id from canton_cr where codigo_canton ='01' and provincia_id = 4),'Varablanca'),
 ('01',(select id from canton_cr where codigo_canton ='02' and provincia_id = 4),'Barva'),
 ('02',(select id from canton_cr where codigo_canton ='02' and provincia_id = 4),'San Pedro'),
 ('03',(select id from canton_cr where codigo_canton ='02' and provincia_id = 4),'San Pablo'),
 ('04',(select id from canton_cr where codigo_canton ='02' and provincia_id = 4),'San Roque'),
 ('05',(select id from canton_cr where codigo_canton ='02' and provincia_id = 4),'Santa Lucía'),
 ('06',(select id from canton_cr where codigo_canton ='02' and provincia_id = 4),'San José de la Montaña'),
 ('01',(select id from canton_cr where codigo_canton ='03' and provincia_id = 4),'Santo Domingo'),
 ('02',(select id from canton_cr where codigo_canton ='03' and provincia_id = 4),'San Vicente'),
 ('03',(select id from canton_cr where codigo_canton ='03' and provincia_id = 4),'San Miguel'),
 ('04',(select id from canton_cr where codigo_canton ='03' and provincia_id = 4),'Paracito'),
 ('05',(select id from canton_cr where codigo_canton ='03' and provincia_id = 4),'Santo Tomás'),
 ('06',(select id from canton_cr where codigo_canton ='03' and provincia_id = 4),'Santa Rosa'),
 ('07',(select id from canton_cr where codigo_canton ='03' and provincia_id = 4),'Tures'),
 ('08',(select id from canton_cr where codigo_canton ='03' and provincia_id = 4),'Pará'),
 ('01',(select id from canton_cr where codigo_canton ='04' and provincia_id = 4),'Santa Bárbara'),
 ('02',(select id from canton_cr where codigo_canton ='04' and provincia_id = 4),'San Pedro'),
 ('03',(select id from canton_cr where codigo_canton ='04' and provincia_id = 4),'San Juan'),
 ('04',(select id from canton_cr where codigo_canton ='04' and provincia_id = 4),'Jesús'),
 ('05',(select id from canton_cr where codigo_canton ='04' and provincia_id = 4),'Santo Domingo del Roble'),
 ('06',(select id from canton_cr where codigo_canton ='04' and provincia_id = 4),'Puraba'),
 ('01',(select id from canton_cr where codigo_canton ='05' and provincia_id = 4),'San Rafael'),
 ('02',(select id from canton_cr where codigo_canton ='05' and provincia_id = 4),'San Josecito'),
 ('03',(select id from canton_cr where codigo_canton ='05' and provincia_id = 4),'Santiago'),
 ('04',(select id from canton_cr where codigo_canton ='05' and provincia_id = 4),'Angeles'),
 ('05',(select id from canton_cr where codigo_canton ='05' and provincia_id = 4),'Concepción'),
 ('01',(select id from canton_cr where codigo_canton ='06' and provincia_id = 4),'San Isidro'),
 ('02',(select id from canton_cr where codigo_canton ='06' and provincia_id = 4),'San José'),
 ('03',(select id from canton_cr where codigo_canton ='06' and provincia_id = 4),'Concepción'),
 ('04',(select id from canton_cr where codigo_canton ='06' and provincia_id = 4),'San Francisco'),
 ('01',(select id from canton_cr where codigo_canton ='07' and provincia_id = 4),'San Antonio'),
 ('02',(select id from canton_cr where codigo_canton ='07' and provincia_id = 4),'La Ribera'),
 ('03',(select id from canton_cr where codigo_canton ='07' and provincia_id = 4),'Asunción'),
 ('01',(select id from canton_cr where codigo_canton ='08' and provincia_id = 4),'San Joaquín'),
 ('02',(select id from canton_cr where codigo_canton ='08' and provincia_id = 4),'Barrantes'),
 ('03',(select id from canton_cr where codigo_canton ='08' and provincia_id = 4),'Llorente'),
 ('01',(select id from canton_cr where codigo_canton ='09' and provincia_id = 4),'San Pablo'),
 ('01',(select id from canton_cr where codigo_canton ='10' and provincia_id = 4),'Puerto Viejo'),
 ('02',(select id from canton_cr where codigo_canton ='10' and provincia_id = 4),'La Virgen'),
 ('03',(select id from canton_cr where codigo_canton ='10' and provincia_id = 4),'Horquetas'),
 ('04',(select id from canton_cr where codigo_canton ='10' and provincia_id = 4),'Llanuras de Gaspar'),
 ('05',(select id from canton_cr where codigo_canton ='10' and provincia_id = 4),'Cureña'),
 ('01',(select id from canton_cr where codigo_canton ='01' and provincia_id = 5),'Liberia'),
 ('02',(select id from canton_cr where codigo_canton ='01' and provincia_id = 5),'Cañas Dulces'),
 ('03',(select id from canton_cr where codigo_canton ='01' and provincia_id = 5),'Mayorga'),
 ('04',(select id from canton_cr where codigo_canton ='01' and provincia_id = 5),'Nacascolo'),
 ('05',(select id from canton_cr where codigo_canton ='01' and provincia_id = 5),'Curubande'),
 ('01',(select id from canton_cr where codigo_canton ='02' and provincia_id = 5),'Nicoya'),
 ('02',(select id from canton_cr where codigo_canton ='02' and provincia_id = 5),'Mansión'),
 ('03',(select id from canton_cr where codigo_canton ='02' and provincia_id = 5),'San Antonio'),
 ('04',(select id from canton_cr where codigo_canton ='02' and provincia_id = 5),'Quebrada Honda'),
 ('05',(select id from canton_cr where codigo_canton ='02' and provincia_id = 5),'Sámara'),
 ('06',(select id from canton_cr where codigo_canton ='02' and provincia_id = 5),'Nósara'),
 ('07',(select id from canton_cr where codigo_canton ='02' and provincia_id = 5),'Belén de Nosarita'),
 ('01',(select id from canton_cr where codigo_canton ='03' and provincia_id = 5),'Santa Cruz'),
 ('02',(select id from canton_cr where codigo_canton ='03' and provincia_id = 5),'Bolsón'),
 ('03',(select id from canton_cr where codigo_canton ='03' and provincia_id = 5),'Veintisiete de Abril'),
 ('04',(select id from canton_cr where codigo_canton ='03' and provincia_id = 5),'Tempate'),
 ('05',(select id from canton_cr where codigo_canton ='03' and provincia_id = 5),'Cartagena'),
 ('06',(select id from canton_cr where codigo_canton ='03' and provincia_id = 5),'Cuajiniquil'),
 ('07',(select id from canton_cr where codigo_canton ='03' and provincia_id = 5),'Diriá'),
 ('08',(select id from canton_cr where codigo_canton ='03' and provincia_id = 5),'Cabo Velas'),
 ('09',(select id from canton_cr where codigo_canton ='03' and provincia_id = 5),'Tamarindo'),
 ('01',(select id from canton_cr where codigo_canton ='04' and provincia_id = 5),'Bagaces'),
 ('02',(select id from canton_cr where codigo_canton ='04' and provincia_id = 5),'Fortuna'),
 ('03',(select id from canton_cr where codigo_canton ='04' and provincia_id = 5),'Mogote'),
 ('04',(select id from canton_cr where codigo_canton ='04' and provincia_id = 5),'Río Naranjo'),
 ('01',(select id from canton_cr where codigo_canton ='05' and provincia_id = 5),'Filadelfia'),
 ('02',(select id from canton_cr where codigo_canton ='05' and provincia_id = 5),'Palmira'),
 ('03',(select id from canton_cr where codigo_canton ='05' and provincia_id = 5),'Sardinal'),
 ('04',(select id from canton_cr where codigo_canton ='05' and provincia_id = 5),'Belén'),
 ('01',(select id from canton_cr where codigo_canton ='06' and provincia_id = 5),'Cañas'),
 ('02',(select id from canton_cr where codigo_canton ='06' and provincia_id = 5),'Palmira'),
 ('03',(select id from canton_cr where codigo_canton ='06' and provincia_id = 5),'San Miguel'),
 ('04',(select id from canton_cr where codigo_canton ='06' and provincia_id = 5),'Bebedero'),
 ('05',(select id from canton_cr where codigo_canton ='06' and provincia_id = 5),'Porozal'),
 ('01',(select id from canton_cr where codigo_canton ='07' and provincia_id = 5),'Juntas'),
 ('02',(select id from canton_cr where codigo_canton ='07' and provincia_id = 5),'Sierra'),
 ('03',(select id from canton_cr where codigo_canton ='07' and provincia_id = 5),'San Juan'),
 ('04',(select id from canton_cr where codigo_canton ='07' and provincia_id = 5),'Colorado'),
 ('01',(select id from canton_cr where codigo_canton ='08' and provincia_id = 5),'Tilarán'),
 ('02',(select id from canton_cr where codigo_canton ='08' and provincia_id = 5),'Quebrada Grande'),
 ('03',(select id from canton_cr where codigo_canton ='08' and provincia_id = 5),'Tronadora'),
 ('04',(select id from canton_cr where codigo_canton ='08' and provincia_id = 5),'Santa Rosa'),
 ('05',(select id from canton_cr where codigo_canton ='08' and provincia_id = 5),'Líbano'),
 ('06',(select id from canton_cr where codigo_canton ='08' and provincia_id = 5),'Tierras Morenas'),
 ('07',(select id from canton_cr where codigo_canton ='08' and provincia_id = 5),'Arenal'),
 ('01',(select id from canton_cr where codigo_canton ='09' and provincia_id = 5),'Carmona'),
 ('02',(select id from canton_cr where codigo_canton ='09' and provincia_id = 5),'Santa Rita'),
 ('03',(select id from canton_cr where codigo_canton ='09' and provincia_id = 5),'Zapotal'),
 ('04',(select id from canton_cr where codigo_canton ='09' and provincia_id = 5),'San Pablo'),
 ('05',(select id from canton_cr where codigo_canton ='09' and provincia_id = 5),'Porvenir'),
 ('06',(select id from canton_cr where codigo_canton ='09' and provincia_id = 5),'Bejuco'),
 ('01',(select id from canton_cr where codigo_canton ='10' and provincia_id = 5),'La Cruz'),
 ('02',(select id from canton_cr where codigo_canton ='10' and provincia_id = 5),'Santa Cecilia'),
 ('03',(select id from canton_cr where codigo_canton ='10' and provincia_id = 5),'Garita'),
 ('04',(select id from canton_cr where codigo_canton ='10' and provincia_id = 5),'Santa Elena'),
 ('01',(select id from canton_cr where codigo_canton ='11' and provincia_id = 5),'Hojancha'),
 ('02',(select id from canton_cr where codigo_canton ='11' and provincia_id = 5),'Monte Romo'),
 ('03',(select id from canton_cr where codigo_canton ='11' and provincia_id = 5),'Puerto Carrillo'),
 ('04',(select id from canton_cr where codigo_canton ='11' and provincia_id = 5),'Huacas'),
 ('01',(select id from canton_cr where codigo_canton ='01' and provincia_id = 6),'Puntarenas'),
 ('02',(select id from canton_cr where codigo_canton ='01' and provincia_id = 6),'Pitahaya'),
 ('03',(select id from canton_cr where codigo_canton ='01' and provincia_id = 6),'Chomes'),
 ('04',(select id from canton_cr where codigo_canton ='01' and provincia_id = 6),'Lepanto'),
 ('05',(select id from canton_cr where codigo_canton ='01' and provincia_id = 6),'Paquera'),
 ('06',(select id from canton_cr where codigo_canton ='01' and provincia_id = 6),'Manzanillo'),
 ('07',(select id from canton_cr where codigo_canton ='01' and provincia_id = 6),'Guacimal'),
 ('08',(select id from canton_cr where codigo_canton ='01' and provincia_id = 6),'Barranca'),
 ('09',(select id from canton_cr where codigo_canton ='01' and provincia_id = 6),'Monte Verde'),
 ('10',(select id from canton_cr where codigo_canton ='01' and provincia_id = 6),'Isla del Coco'),
 ('11',(select id from canton_cr where codigo_canton ='01' and provincia_id = 6),'Cóbano'),
 ('12',(select id from canton_cr where codigo_canton ='01' and provincia_id = 6),'Chacarita'),
 ('13',(select id from canton_cr where codigo_canton ='01' and provincia_id = 6),'Chira'),
 ('14',(select id from canton_cr where codigo_canton ='01' and provincia_id = 6),'Acapulco'),
 ('15',(select id from canton_cr where codigo_canton ='01' and provincia_id = 6),'Roble'),
 ('16',(select id from canton_cr where codigo_canton ='01' and provincia_id = 6),'Arancibia'),
 ('01',(select id from canton_cr where codigo_canton ='02' and provincia_id = 6),'Espíritu Santo'),
 ('02',(select id from canton_cr where codigo_canton ='02' and provincia_id = 6),'San Juan Grande'),
 ('03',(select id from canton_cr where codigo_canton ='02' and provincia_id = 6),'Macacona'),
 ('04',(select id from canton_cr where codigo_canton ='02' and provincia_id = 6),'San Rafael'),
 ('05',(select id from canton_cr where codigo_canton ='02' and provincia_id = 6),'San Jerónimo'),
 ('01',(select id from canton_cr where codigo_canton ='03' and provincia_id = 6),'Buenos Aires'),
 ('02',(select id from canton_cr where codigo_canton ='03' and provincia_id = 6),'Volcán'),
 ('03',(select id from canton_cr where codigo_canton ='03' and provincia_id = 6),'Potrero Grande'),
 ('04',(select id from canton_cr where codigo_canton ='03' and provincia_id = 6),'Boruca'),
 ('05',(select id from canton_cr where codigo_canton ='03' and provincia_id = 6),'Pilas'),
 ('06',(select id from canton_cr where codigo_canton ='03' and provincia_id = 6),'Colinas o Bajo de Maíz'),
 ('07',(select id from canton_cr where codigo_canton ='03' and provincia_id = 6),'Chánguena'),
 ('08',(select id from canton_cr where codigo_canton ='03' and provincia_id = 6),'Bioley'),
 ('09',(select id from canton_cr where codigo_canton ='03' and provincia_id = 6),'Brunka'),
 ('01',(select id from canton_cr where codigo_canton ='04' and provincia_id = 6),'Miramar'),
 ('02',(select id from canton_cr where codigo_canton ='04' and provincia_id = 6),'Unión'),
 ('03',(select id from canton_cr where codigo_canton ='04' and provincia_id = 6),'San Isidro'),
 ('01',(select id from canton_cr where codigo_canton ='05' and provincia_id = 6),'Puerto Cortés'),
 ('02',(select id from canton_cr where codigo_canton ='05' and provincia_id = 6),'Palmar'),
 ('03',(select id from canton_cr where codigo_canton ='05' and provincia_id = 6),'Sierpe'),
 ('04',(select id from canton_cr where codigo_canton ='05' and provincia_id = 6),'Bahía Ballena'),
 ('05',(select id from canton_cr where codigo_canton ='05' and provincia_id = 6),'Piedras Blancas'),
 ('01',(select id from canton_cr where codigo_canton ='06' and provincia_id = 6),'Quepos'),
 ('02',(select id from canton_cr where codigo_canton ='06' and provincia_id = 6),'Savegre'),
 ('03',(select id from canton_cr where codigo_canton ='06' and provincia_id = 6),'Naranjito'),
 ('01',(select id from canton_cr where codigo_canton ='07' and provincia_id = 6),'Golfito'),
 ('02',(select id from canton_cr where codigo_canton ='07' and provincia_id = 6),'Puerto Jiménez'),
 ('03',(select id from canton_cr where codigo_canton ='07' and provincia_id = 6),'Guaycará'),
 ('04',(select id from canton_cr where codigo_canton ='07' and provincia_id = 6),'Pavon'),
 ('01',(select id from canton_cr where codigo_canton ='08' and provincia_id = 6),'San Vito'),
 ('02',(select id from canton_cr where codigo_canton ='08' and provincia_id = 6),'Sabalito'),
 ('03',(select id from canton_cr where codigo_canton ='08' and provincia_id = 6),'Agua Buena'),
 ('04',(select id from canton_cr where codigo_canton ='08' and provincia_id = 6),'Limoncito'),
 ('05',(select id from canton_cr where codigo_canton ='08' and provincia_id = 6),'Pittier'),
 ('01',(select id from canton_cr where codigo_canton ='09' and provincia_id = 6),'Parrita'),
 ('01',(select id from canton_cr where codigo_canton ='10' and provincia_id = 6),'Corredor'),
 ('02',(select id from canton_cr where codigo_canton ='10' and provincia_id = 6),'La Cuesta'),
 ('03',(select id from canton_cr where codigo_canton ='10' and provincia_id = 6),'Paso Canoas'),
 ('04',(select id from canton_cr where codigo_canton ='10' and provincia_id = 6),'Laurel'),
 ('01',(select id from canton_cr where codigo_canton ='11' and provincia_id = 6),'Jacó'),
 ('02',(select id from canton_cr where codigo_canton ='11' and provincia_id = 6),'Tárcoles'),
 ('01',(select id from canton_cr where codigo_canton ='01' and provincia_id = 7),'Limón'),
 ('02',(select id from canton_cr where codigo_canton ='01' and provincia_id = 7),'Valle La Estrella'),
 ('03',(select id from canton_cr where codigo_canton ='01' and provincia_id = 7),'Río Blanco'),
 ('04',(select id from canton_cr where codigo_canton ='01' and provincia_id = 7),'Matama'),
 ('01',(select id from canton_cr where codigo_canton ='02' and provincia_id = 7),'Guápiles'),
 ('02',(select id from canton_cr where codigo_canton ='02' and provincia_id = 7),'Jiménez'),
 ('03',(select id from canton_cr where codigo_canton ='02' and provincia_id = 7),'Rita'),
 ('04',(select id from canton_cr where codigo_canton ='02' and provincia_id = 7),'Roxana'),
 ('05',(select id from canton_cr where codigo_canton ='02' and provincia_id = 7),'Cariari'),
 ('06',(select id from canton_cr where codigo_canton ='02' and provincia_id = 7),'Colorado'),
 ('01',(select id from canton_cr where codigo_canton ='03' and provincia_id = 7),'Siquirres'),
 ('02',(select id from canton_cr where codigo_canton ='03' and provincia_id = 7),'Pacuarito'),
 ('03',(select id from canton_cr where codigo_canton ='03' and provincia_id = 7),'Florida'),
 ('04',(select id from canton_cr where codigo_canton ='03' and provincia_id = 7),'Germania'),
 ('05',(select id from canton_cr where codigo_canton ='03' and provincia_id = 7),'Cairo'),
 ('06',(select id from canton_cr where codigo_canton ='03' and provincia_id = 7),'Alegría'),
 ('01',(select id from canton_cr where codigo_canton ='04' and provincia_id = 7),'Bratsi'),
 ('02',(select id from canton_cr where codigo_canton ='04' and provincia_id = 7),'Sixaola'),
 ('03',(select id from canton_cr where codigo_canton ='04' and provincia_id = 7),'Cahuita'),
 ('04',(select id from canton_cr where codigo_canton ='04' and provincia_id = 7),'Telire'),
 ('01',(select id from canton_cr where codigo_canton ='05' and provincia_id = 7),'Matina'),
 ('02',(select id from canton_cr where codigo_canton ='05' and provincia_id = 7),'Batán'),
 ('03',(select id from canton_cr where codigo_canton ='05' and provincia_id = 7),'Carrandí'),
 ('01',(select id from canton_cr where codigo_canton ='06' and provincia_id = 7),'Guácimo'),
 ('02',(select id from canton_cr where codigo_canton ='06' and provincia_id = 7),'Mercedes'),
 ('03',(select id from canton_cr where codigo_canton ='06' and provincia_id = 7),'Pocora'),
 ('04',(select id from canton_cr where codigo_canton ='06' and provincia_id = 7),'Río Jiménez'),
 ('05',(select id from canton_cr where codigo_canton ='06' and provincia_id = 7),'Duacarí');   							 
  

ALTER TABLE `distrito_cr` MODIFY canton_id int(11) NOT NULL;

ALTER TABLE `distrito_cr`
    ADD CONSTRAINT `FK_DISTRITO_CANTON` FOREIGN KEY (`canton_id`) REFERENCES `canton_cr` (`id`);





